# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M9XU53CcFDRH2KLQD1Ln2gPcXO5cxD7Y
"""

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# Load the dataset
file_path = '/content/sample_data/DATASETCOMP.xlsx'
df = pd.read_excel(file_path)

# Keep only the first 30 companies
df = df.head(30)

# Clean columns if necessary
df.columns = df.columns.str.strip()

# Identify columns globally to avoid NameErrors in other cells
emp_col = [c for c in df.columns if 'employee' in c.lower()][0]
comp_col = [c for c in df.columns if 'name' in c.lower() or 'company' in c.lower()][0]
rev_col = [c for c in df.columns if 'review' in c.lower()][0]
hq_col = [c for c in df.columns if 'hq' in c.lower() or 'headquarter' in c.lower()][0]
rate_col = [c for c in df.columns if 'rating' in c.lower()][0]
year_col = [c for c in df.columns if 'year' in c.lower() or 'founded' in c.lower()][0]

display(df.head())

"""### 1. Pie Chart: Companies Employee Wise"""

# The 'employees' column contains strings, so we count the frequency of each category
emp_counts = df[emp_col].value_counts().reset_index()
emp_counts.columns = [emp_col, 'count']

fig1 = px.pie(emp_counts, values='count', names=emp_col, title='Distribution of Companies by Employee Size')
fig1.show()

"""### 2. Funnel Chart: Companies Review Wise"""

rev_col = [c for c in df.columns if 'review' in c.lower()][0]
# Sorting by reviews to make the funnel look correct
df_funnel = df.sort_values(by=rev_col, ascending=False)

fig2 = px.funnel(df_funnel, x=rev_col, y=comp_col, title='Companies Review Wise')
fig2.show()

"""### 3. Name of Headquarters Company Wise (First 10)"""

hq_col = [c for c in df.columns if 'hq' in c.lower() or 'headquarter' in c.lower()][0]
display(df[[comp_col, hq_col]].head(10))

"""### 4. Bar Chart: Companies Rating Wise"""

rate_col = [c for c in df.columns if 'rating' in c.lower()][0]
fig3 = px.bar(df, x=comp_col, y=rate_col, title='Companies Rating Wise', color=rate_col)
fig3.show()

"""### 5. Line Chart: Companies Year Wise"""

year_col = [c for c in df.columns if 'year' in c.lower() or 'founded' in c.lower()][0]
# Sort by year for a meaningful line chart
df_year = df.sort_values(by=year_col)

fig4 = px.line(df_year, x=year_col, y=comp_col, title='Companies Year Wise (Establishment Trend)', markers=True)
fig4.show()